version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - kinesis
      - postgresql

  kinesis:
    image: saidsef/aws-kinesis-local
    ports:
      - "4567:4567"

  postgresql:
    image: postgres:15.1
    environment:
      - POSTGRES_PASSWORD=changeMe
    ports:
      - "5432:5432"